# Generated by Django 3.2 on 2022-03-26 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test',
            new_name='Contact',
        ),
    ]
