# Generated by Django 3.2 on 2022-03-26 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_rename_test_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='complete',
        ),
    ]
