# Generated by Django 3.2 on 2022-03-26 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_remove_contact_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='detail',
            new_name='cost',
        ),
    ]
