# Generated by Django 3.2 on 2022-03-26 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_rename_detail_contact_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='description',
        ),
    ]
