# Generated by Django 3.2 on 2022-03-30 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='point',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
