# Generated by Django 3.2 on 2022-03-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_resetpasswordtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified_token',
            field=models.CharField(default='no token', max_length=100),
        ),
    ]
