# Generated by Django 3.2 on 2022-04-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_rename_point_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='specfile'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
    ]
